---

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

env:
  node: true
  jest: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

rules:
  no-console: 0
